# This is a sample playbook to launch an AWS Virtual Machine
---

# Launch VMs
- name: Launch VM instances
  hosts: localhost
  connection: local
  gather_facts: false
  tasks: 
  - name: Create an EC2 instance
    ec2:
      key_name: "{{ key_name }}"
      region: "{{ aws_region }}"
      group_id: "{{ sec_group_output.group_id }}"
      instance_type: "{{ instance_type }}"
      image: "{{ ami_id }}"
      instance_tags:
        Name: definiens
      vpc_subnet_id: "{{ vpc_subnet_id }}"
      wait: yes
      volumes:
        - device_name: /dev/sda1
          volume_type: gp2
          volume_size: 10
          delete_on_termination: true
      count: 2
    register: ec2


## This is to be used instead of sleeping the sh file. I need to see why it didn't work
#
#
#  - name: Wait for ssh to start
#    wait_for:
#      host: "{{ item.public_dns_name }}" 
#      port: 22
#      delay: 30
#      timeout: 180
#      state: started
#    with_items: "{{ ec2.instances }}"

